cursor_ = (# 16x16
  "...             ",
  ".X.             ",
  "...             ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ",
  "                ")

cursor_norm = (# 16x16
  "..              ",
  ".X.             ",
  ".XX.            ",
  ".XXX.           ",
  ".XXXX.          ",
  ".XXXXX.         ",
  ".XXXXXX.        ",
  ".XXXXXXX.       ",
  ".XXXXXXXX.      ",
  ".XXXXXXXXX.     ",
  ".XXXXXXXXXX.    ",
  ".XXXX.......    ",
  ".XXX.           ",
  ".XX.            ",
  ".X.             ",
  "..              ")

cursor_rect = (# 16x16
  "... ............",
  ".X. .XXXXXXXXXX.",
  "... .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    ............",
  "                ",
  "                ",
  "                ",
  "                ")

cursor_rcte = (# 16x16
  "... ............",
  ".X. .XXXXXXXXXX.",
  "... .X........X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X........X.",
  "    .XXXXXXXXXX.",
  "    ............",
  "                ",
  "                ",
  "                ",
  "                ")

cursor_oval = (# 16x16
  "...     ....    ",
  ".X.   ..XXXX..  ",
  "...  .XXXXXXXX. ",
  "     .XXXXXXXX. ",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "    .XXXXXXXXXX.",
  "     .XXXXXXXX. ",
  "     .XXXXXXXX. ",
  "      ..XXXX..  ",
  "        ....    ",
  "                ",
  "                ",
  "                ",
  "                ")

cursor_ovle = (# 16x16
  "...     ....    ",
  ".X.   ..XXXX..  ",
  "...  .XX....XX. ",
  "     .X.    .X. ",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "    .X.      .X.",
  "     .X.    .X. ",
  "     .XX....XX. ",
  "      ..XXXX..  ",
  "        ....    ",
  "                ",
  "                ",
  "                ",
  "                ")

cursor_pick = (# 16x16
  "..              ",
  ".X.             ",
  " .X..           ",
  "  .XX.          ",
  "  .XXX.         ",
  "   .X  .        ",
  "    .   .       ",
  "     .   .      ",
  "      .   .     ",
  "       .   .    ",
  "        .   ... ",
  "         .  XX..",
  "          .XXXX.",
  "          .XXXX.",
  "          ..XX. ",
  "           ...  ")

cursor_draw = (# 16x16
  "...             ",
  ".XX.            ",
  ".XX..           ",
  " ..XX.          ",
  "  .XXX.         ",
  "   .XXX.        ",
  "    .XXX.       ",
  "     .XXX.      ",
  "      .XXX.     ",
  "       .XXX.    ",
  "        .XXX.   ",
  "         .XX..  ",
  "          ..X.. ",
  "           ..XX.",
  "            .XX.",
  "             .. ")

cursor_line = (# 16x16
  "... .           ",
  ".X..X.          ",
  "...XXX.         ",
  " .XXXXX.        ",
  ".X.XXXXX.       ",
  " .XXX.XXX.      ",
  "  .X.XXXXX.     ",
  "   .XXXXXXX.    ",
  "    .X.XXXXX.   ",
  "     .XXX.XXX.  ",
  "      .X.XXXXX. ",
  "       .XXXXXXX.",
  "        .X.XXX. ",
  "         .XXX.  ",
  "          .X.   ",
  "           .    ")

cursor_fill = (# 16x16
  "................",
  ".XX.X.XXXXXXX.X.",
  ".X. .X.XXXXXX.X.",
  ".X.  .X.XXXXX.X.",
  " .   .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.XXXXX.X.",
  "     .X.......X.",
  "     .XXXXXXXXX.",
  "     .XXXXXXXXX.",
  "     ...........")

